[build]
  command = "npm install && ng build --configuration production"
  publish = "dist/tpi-teg-fe-tpi-teg/browser"

[[redirects]]
  from = "/api/*"
  to = "https://4068-2803-9800-9897-91b5-44f9-3da9-7530-df6d.ngrok-free.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
