[build]
command = "ng build --configuration production"
publish = "dist/tpi-teg-fe-tpi-teg"

[[redirects]]
from = "/api/*"
to = "https://2afc-2803-9800-9897-91b5-d08e-2075-fbcd-41e1.ngrok-free.app/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[plugins]
package = "@netlify/plugin-angular"
inputs = { disableRuntime = true }
