[build]
command = "ng build --configuration production"
publish = "dist"

# Proxy para redirigir llamadas a /api hacia tu backend
[[redirects]]
from = "/api/*"
to = "https://2afc-2803-9800-9897-91b5-d08e-2075-fbcd-41e1.ngrok-free.app/:splat"
status = 200
force = true

# Fallback para SPA (Single Page App)
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
