[build]
  command = "npm install && ng build --configuration production"
  publish = "dist/tpi-teg-fe-tpi-teg/browser"

[[redirects]]
  from = "/api/*"
  to = "https://7fc1-190-114-208-144.ngrok-free.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
